import { readFileSync, writeFileSync } from "fs";

/**
 * Banner stamped onto every runtime file the CLI copies into a consumer's tree.
 *
 * These files are copied verbatim, so what a consumer sees is ordinary-looking
 * source with nothing to say where it came from. The failure mode that motivates
 * the banner: a linter flags something in the vendored copy, someone fixes it in
 * place, and the next `binschema generate` silently reverts the fix — because
 * the copy is downstream of binschema's own runtime source, and nothing in the
 * file says so. That loop has already cost a real debugging session downstream.
 *
 * Naming the upstream directory turns it into a one-line instruction.
 *
 * @param upstreamDir Path to the source directory *within the binschema repo*,
 *   so the reader knows exactly which file to change.
 * @param commentPrefix Line-comment token for the target language (`#` for
 *   Python, `//` for everything else).
 */
export function vendoredRuntimeBanner(upstreamDir: string, commentPrefix = "//"): string {
  const c = commentPrefix;
  return [
    `${c} @generated by binschema — DO NOT EDIT.`,
    `${c}`,
    `${c} Copied verbatim from the binschema repo (${upstreamDir}) every time`,
    `${c} bindings are regenerated. Any edit made here — including a lint fix —`,
    `${c} is silently reverted by the next \`binschema generate\` run. Change the`,
    `${c} upstream file instead, then regenerate.`,
    "",
    "",
  ].join("\n");
}

/**
 * Copy one runtime file into a consumer's tree, stamping the vendored-file
 * banner onto it.
 *
 * The banner ends with a blank line, and that blank line is doing real work in
 * two languages: Go treats a comment sitting immediately above `package x` as
 * the package doc comment, and Zig/Rust do the same for the first declaration.
 * Without the separator the banner would silently replace whatever
 * documentation the runtime file actually carries.
 */
export function copyRuntimeFile(
  srcPath: string,
  destPath: string,
  upstreamDir: string,
  commentPrefix = "//",
): void {
  const content = readFileSync(srcPath, "utf-8");
  writeFileSync(destPath, vendoredRuntimeBanner(upstreamDir, commentPrefix) + content, "utf-8");
}
