// ABOUTME: Zig code generator entry point + per-type emit dispatch.
// ABOUTME: Reference implementation is src/generators/typescript.ts; structurally mirrors python.ts.
//
// Phase 1 scope: struct types whose fields are byte-aligned primitives or bit
// fields, with full ctx/root threading in every emitted encode/decode. All
// other type kinds (enum, discriminated_union, string, array, back_reference)
// and richer field kinds throw ZigNotImplemented so the test harness records a
// clean per-suite gap instead of emitting broken Zig. Later phases fill these in.

import { type BinarySchema, isEnumType } from "../../schema/binary-schema.js";
import {
  RT,
  ENC,
  CTX,
  DEC,
  ROOT,
  ALLOC,
  ERR,
  encodeParams,
  encodeArgs,
  decodeParams,
  decodeArgs,
} from "./context.js";
import { resetVarCounter, zigFieldName, zigTypeName } from "./naming.js";
import { zigBitOrder, zigDeclaredType, zigPrimitiveType, varlengthWriteMethod } from "./types.js";
import { generateFieldEncode, emitEncodeValue, ZigNotImplemented, type EmitCtx } from "./encode.js";
import { generateFieldDecode, emitDecodeValue } from "./decode.js";
import { generateEnumCode } from "./enum.js";
import { collectUnionTypes } from "./union.js";
import {
  computedTargets,
  emitComputedBackpatch,
  fieldOffVar,
  fieldEndVar,
  frameStartVar,
  schemaHasParentRefs,
  schemaHasSelectors,
  emitFrameLengthRegistration,
} from "./computed.js";

export interface GeneratedZigCode {
  code: string;
  typeName: string;
}

export interface ZigGeneratorOptions {
  /** Module name for the runtime import (default: "binschema"). */
  runtimeModule?: string;
}

export function generateZig(
  schema: BinarySchema,
  typeName: string,
  options?: ZigGeneratorOptions,
): GeneratedZigCode {
  const runtimeModule = options?.runtimeModule || RT;

  if (!schema.types[typeName]) {
    throw new Error(`Type ${typeName} not found in schema`);
  }

  const defaultEndianness = schema.config?.endianness || "big_endian";
  const defaultBitOrder = schema.config?.bit_order || "msb_first";

  const lines: string[] = [];
  lines.push(`// Generated by BinSchema — do not edit manually`);
  lines.push(`const std = @import("std");`);
  lines.push(`const ${RT} = @import("${runtimeModule}");`);
  lines.push(``);

  // Named tagged-union types for every distinct choice/DU shape. Emitted once at
  // container scope so a `[]const UnionName` field and an `alloc(UnionName, n)` in
  // decode reference the SAME Zig type (anonymous `union(enum){…}` literals at
  // different sites are distinct types and would not be assignable).
  const unionTypes = collectUnionTypes(schema);
  if (unionTypes.length > 0) {
    for (const u of unionTypes) lines.push(`pub const ${u.name} = ${u.body};`);
    lines.push(``);
  }

  for (const [name, typeDef] of Object.entries(schema.types)) {
    if (name.includes("<")) continue; // skip generic templates

    if ("sequence" in (typeDef as any)) {
      // Types carrying `instances` (lazily-decoded, position-referenced fields)
      // affect the wire layout beyond the plain sequence — random access is a
      // later phase. Reject cleanly rather than emit a sequence-only struct
      // that silently produces wrong bytes.
      if (Array.isArray((typeDef as any).instances) && (typeDef as any).instances.length > 0) {
        throw new ZigNotImplemented(`type '${name}' with instances (random access, Phase 3)`);
      }
      lines.push(...generateStructCode(name, typeDef as any, schema, defaultEndianness, defaultBitOrder));
    } else if (isEnumType(typeDef as any)) {
      lines.push(...generateEnumCode(name, typeDef as any, defaultEndianness, defaultBitOrder));
    } else if ((typeDef as any).type === "discriminated_union" || (typeDef as any).type === "choice") {
      // Named DU/choice types map to a shared named union (emitted above by
      // collectUnionTypes) and have encode/decode inlined into each referencing
      // parent. Nothing further to emit here.
    } else if (
      (typeDef as any).type === "string" ||
      (typeDef as any).type === "bytes" ||
      (typeDef as any).type === "array"
    ) {
      // String/bytes/array named types have no Zig type of their own —
      // referencing fields resolve them inline to []const u8 / []const Item.
      // We still emit free encode/decode functions so the type can be used as a
      // top-level entry point (e.g. a DNS Label encoded on its own).
      lines.push(...generateAliasFunctions(name, typeDef as any, schema, defaultEndianness, defaultBitOrder));
    } else if ((typeDef as any).type === "back_reference") {
      throw new ZigNotImplemented(`back_reference type '${name}' (Phase 5)`);
    }
    lines.push(``);
  }

  return { code: lines.join("\n"), typeName };
}

/** Emit a Zig struct with threaded encode/decode for a `sequence` type. */
function generateStructCode(
  name: string,
  typeDef: any,
  schema: BinarySchema,
  endianness: string,
  bitOrder: string,
): string[] {
  resetVarCounter();
  const typeNameZ = zigTypeName(name);
  const fields = typeDef.sequence || [];
  const bo = zigBitOrder(bitOrder, "msb_first");

  const emit: EmitCtx = { schema, endianness, bitOrder, selfPath: "self", fields, selfTypeName: name };
  // When the schema uses any `../` parent reference, every struct pushes a
  // parent frame and records its fields' lengths/ranges so descendant computed
  // fields can resolve cross-struct references. Schemas with no such ref keep
  // the lean Phase-2 path (no frames emitted at all).
  const framesOn = schemaHasParentRefs(schema) && fields.length > 0;
  // Selectors (first/last/corresponding) register deferred selector_position
  // patches that must be resolved after the whole tree is encoded — even when
  // the schema has no `../` parent ref to turn frames on.
  const needsResolve = framesOn || schemaHasSelectors(schema);

  const lines: string[] = [];
  lines.push(`pub const ${typeNameZ} = struct {`);

  // Field declarations. Computed and const fields are omitted by callers (the
  // value is supplied by the wire / computed on encode), so they get a default
  // so the struct can be constructed without them.
  for (const field of fields) {
    // Padding is a pure wire-format spacer with no value — it never becomes a
    // struct member (it's neither supplied on encode nor surfaced on decode).
    if (field.type === "padding") continue;
    const ftype = structFieldType(field, schema);
    const def = fieldDefault(field);
    lines.push(`    ${zigFieldName(field.name)}: ${ftype}${def},`);
  }
  lines.push(``);

  // encode(): allocate encoder+ctx, delegate to encodeInto, finish.
  lines.push(`    pub fn encode(self: ${typeNameZ}, ${ALLOC}: std.mem.Allocator) ${ERR}![]u8 {`);
  lines.push(`        var ${ENC} = ${RT}.BitStreamEncoder.init(${ALLOC}, ${bo});`);
  lines.push(`        errdefer ${ENC}.deinit();`);
  lines.push(`        var ${CTX} = ${RT}.EncodeContext.init(${ALLOC});`);
  lines.push(`        defer ${CTX}.deinit();`);
  lines.push(`        try self.encodeInto(&${ENC}, &${CTX});`);
  if (needsResolve) {
    // Forward references (position_of/crc32_of ../field) and selector_position
    // patches were written as placeholders; resolve them now that the whole tree
    // is encoded.
    lines.push(`        try ${CTX}.resolveDeferredPatches(&${ENC});`);
  }
  lines.push(`        return ${ENC}.finish();`);
  lines.push(`    }`);
  lines.push(``);

  // encodeInto(): the threaded worker. Threaded params (self, ctx) are always
  // present in the signature; we only emit a `_ = x;` discard for the ones this
  // particular struct's body doesn't reference, so the generated Zig compiles
  // without "unused parameter" errors regardless of feature mix.
  lines.push(`    pub fn encodeInto(self: ${typeNameZ}, ${encodeParams()}) ${ERR}!void {`);
  const { posTargets, crcTargets, lenTargets } = computedTargets(fields, schema);
  const encBody: string[] = [];
  const faIdx = fields.findIndex((f: any) => f.computed?.from_after_field);
  if (faIdx >= 0) {
    // A `from_after_field` length prefix needs content-first encoding: write the
    // trailing content to a temp encoder, measure it, then write the varlength
    // length + the content. Keep this path simple — it can't currently combine
    // with parent frames or same-struct position/crc targets.
    if (framesOn || posTargets.size > 0 || crcTargets.size > 0 || lenTargets.size > 0) {
      throw new ZigNotImplemented("from_after_field combined with parent refs / position / crc / measured length");
    }
    for (let i = 0; i < faIdx; i++) encBody.push(...generateFieldEncode(fields[i], emit));
    encBody.push(...emitFromAfterFieldEncode(fields[faIdx], fields.slice(faIdx + 1), emit));
  } else {
    if (framesOn) {
      encBody.push(`        const _frame = try ${CTX}.pushParent();`);
      encBody.push(`        defer ${CTX}.popParent();`);
      // Register fields' length_of values up front so a child's `length_of
      // ../field` (encoded before the field itself) resolves synchronously.
      encBody.push(...emitFrameLengthRegistration(fields, emit, "_frame", "        "));
    }
    for (const field of fields) {
      const tracked = field.name && (posTargets.has(field.name) || crcTargets.has(field.name) || lenTargets.has(field.name));
      if (tracked) {
        encBody.push(`        const ${fieldOffVar(field.name)} = ${ENC}.byteOffset();`);
      }
      if (framesOn && field.name) {
        encBody.push(`        const ${frameStartVar(field.name)} = ${ENC}.byteOffset();`);
      }
      encBody.push(...generateFieldEncode(field, emit));
      if (field.name && (crcTargets.has(field.name) || lenTargets.has(field.name))) {
        encBody.push(`        const ${fieldEndVar(field.name)} = ${ENC}.byteOffset();`);
      }
      if (framesOn && field.name) {
        // Record the field's encoded byte range so descendants' position_of /
        // crc32_of `../field` patches can resolve against it.
        encBody.push(
          `        try ${CTX}.setRange(_frame, "${field.name}", ${frameStartVar(field.name)}, ${ENC}.byteOffset());`,
        );
      }
    }
    encBody.push(...emitComputedBackpatch(fields, emit, "        "));
  }
  lines.push(...discardsFor(encBody, [["self", "self"], [ENC, ENC], [CTX, CTX]]));
  lines.push(...encBody);
  lines.push(`    }`);
  lines.push(``);

  // decode(): construct a decoder and delegate.
  lines.push(`    pub fn decode(${ALLOC}: std.mem.Allocator, bytes: []const u8) ${ERR}!${typeNameZ} {`);
  lines.push(`        var ${DEC} = ${RT}.BitStreamDecoder.init(bytes, ${bo});`);
  lines.push(`        return decodeWith(${ALLOC}, &${DEC}, null);`);
  lines.push(`    }`);
  lines.push(``);

  // decodeWith(): the threaded worker.
  lines.push(`    pub fn decodeWith(${decodeParams()}) ${ERR}!${typeNameZ} {`);
  const decBody: string[] = [];
  for (const field of fields) {
    decBody.push(...generateFieldDecode(field, emit, "result"));
  }
  lines.push(...discardsFor(decBody, [[ALLOC, ALLOC], [DEC, DEC], [ROOT, ROOT]]));
  // An empty struct (no field decodes) never mutates `result`; Zig rejects an
  // unmutated `var`, so declare it `const` in that case.
  const resultDecl = decBody.length === 0 ? "const" : "var";
  lines.push(`        ${resultDecl} result: ${typeNameZ} = undefined;`);
  lines.push(...decBody);
  lines.push(`        return result;`);
  lines.push(`    }`);

  lines.push(`};`);
  return lines;
}

/**
 * Content-first encode for a `from_after_field` length prefix. The length field
 * sits at this position in the wire, but its value is the byte count of all
 * fields that follow it. We encode that trailing content into a temporary
 * encoder (borrowing the outer encoder's allocator + bit order), measure it,
 * then write the varlength length and splice the content into the outer stream.
 *
 * Trailing fields must be plain (non-computed): a computed trailing field would
 * register placeholders/patches against the temp encoder whose offsets don't map
 * to the outer buffer. Such shapes throw ZigNotImplemented (clean skip).
 */
function emitFromAfterFieldEncode(lengthField: any, trailing: any[], emit: EmitCtx, indent = "        "): string[] {
  if (lengthField.type !== "varlength") {
    // The reference generator only supports `from_after_field` on varlength
    // prefixes (content-first sizing). Anything else is an invalid shape.
    throw new ZigNotImplemented(`from_after_field on non-varlength field '${lengthField.name}'`);
  }
  for (const tf of trailing) {
    if (tf.computed || tf.const !== undefined) {
      throw new ZigNotImplemented(`from_after_field with computed/const trailing field '${tf.name}'`);
    }
  }
  const tmp = `_fa_enc_${zigFieldName(lengthField.name)}`;
  const bytesVar = `_fa_bytes_${zigFieldName(lengthField.name)}`;
  const lines: string[] = [];
  lines.push(`${indent}var ${tmp} = ${RT}.BitStreamEncoder.init(${ENC}.allocator, ${ENC}.bit_order);`);
  lines.push(`${indent}defer ${tmp}.deinit();`);
  for (const tf of trailing) {
    // Generated trailing-field encode targets the `enc` identifier; redirect it
    // to the temp encoder. (Trailing fields read their values from `self`.)
    for (const l of generateFieldEncode(tf, emit, indent)) {
      lines.push(l.replace(new RegExp(`\\b${ENC}\\b`, "g"), tmp));
    }
  }
  lines.push(`${indent}const ${bytesVar} = ${tmp}.view();`);
  lines.push(`${indent}try ${ENC}.${varlengthWriteMethod(lengthField)}(@intCast(${bytesVar}.len));`);
  lines.push(`${indent}try ${ENC}.writeBytes(${bytesVar});`);
  return lines;
}

/**
 * For each (token, paramName) pair, emit `_ = paramName;` iff no body line
 * references the token as a whole word. Prevents both unused-param and
 * pointless-discard compile errors.
 */
function discardsFor(body: string[], params: [string, string][], indent = "        "): string[] {
  const out: string[] = [];
  for (const [token, paramName] of params) {
    const re = new RegExp(`\\b${token}\\b`);
    if (!body.some((l) => re.test(l))) out.push(`${indent}_ = ${paramName};`);
  }
  return out;
}

/** Declared Zig type for a struct field. */
function structFieldType(field: any, schema: BinarySchema): string {
  return zigDeclaredType(field, schema);
}

/**
 * Default initializer (`= ...`) for a struct field declaration, or "" for none.
 * Computed and const fields are not provided by callers (they come from the wire
 * / are computed on encode), so they need a default so the Zig struct can be
 * built without them.
 */
function fieldDefault(field: any): string {
  // Optional fields default to null so a struct can be built with them absent.
  if (field.type === "optional") return " = null";
  if (!field.computed && field.const === undefined) return "";
  if (field.type === "bool") return " = false";
  if (field.type === "varlength") return " = 0";
  const prim = zigPrimitiveType(field);
  if (prim === null) {
    throw new ZigNotImplemented(`default for computed/const non-primitive field '${field.name}'`);
  }
  // Integer / float / bit storage: 0 is a safe placeholder (always overwritten).
  return " = 0";
}

/**
 * Emit free `encode<Name>` / `decode<Name>` functions for a top-level
 * string/bytes/array type (one with no Zig type of its own). These let such a
 * type act as a standalone entry point. The value type is its inline Zig
 * representation (`[]const u8` or `[]const Item`).
 */
function generateAliasFunctions(
  name: string,
  typeDef: any,
  schema: BinarySchema,
  endianness: string,
  bitOrder: string,
): string[] {
  resetVarCounter();
  const pascal = zigTypeName(name);
  const valueType = zigDeclaredType(typeDef, schema);
  const bo = zigBitOrder(bitOrder, "msb_first");
  const emit: EmitCtx = { schema, endianness, bitOrder, selfPath: "" };
  const inlineField = { ...typeDef, name: undefined };

  const lines: string[] = [];

  // encode<Name>: build encoder + ctx, delegate, finish.
  lines.push(`pub fn encode${pascal}(value: ${valueType}, ${ALLOC}: std.mem.Allocator) ${ERR}![]u8 {`);
  lines.push(`    var ${ENC} = ${RT}.BitStreamEncoder.init(${ALLOC}, ${bo});`);
  lines.push(`    errdefer ${ENC}.deinit();`);
  lines.push(`    var ${CTX} = ${RT}.EncodeContext.init(${ALLOC});`);
  lines.push(`    defer ${CTX}.deinit();`);
  lines.push(`    try encode${pascal}Into(value, &${ENC}, &${CTX});`);
  if (schemaHasParentRefs(schema) || schemaHasSelectors(schema)) {
    lines.push(`    try ${CTX}.resolveDeferredPatches(&${ENC});`);
  }
  lines.push(`    return ${ENC}.finish();`);
  lines.push(`}`);
  lines.push(``);

  // encode<Name>Into: threaded worker.
  lines.push(`pub fn encode${pascal}Into(value: ${valueType}, ${ENC}: *${RT}.BitStreamEncoder, ${CTX}: *${RT}.EncodeContext) ${ERR}!void {`);
  const encBody = emitEncodeValue(inlineField, "value", emit, "    ");
  lines.push(...discardsFor(encBody, [["value", "value"], [CTX, CTX]], "    "));
  lines.push(...encBody);
  lines.push(`}`);
  lines.push(``);

  // decode<Name>: build decoder, delegate.
  lines.push(`pub fn decode${pascal}(${ALLOC}: std.mem.Allocator, bytes: []const u8) ${ERR}!${valueType} {`);
  lines.push(`    var ${DEC} = ${RT}.BitStreamDecoder.init(bytes, ${bo});`);
  lines.push(`    return decode${pascal}With(${ALLOC}, &${DEC}, null);`);
  lines.push(`}`);
  lines.push(``);

  // decode<Name>With: threaded worker.
  lines.push(`pub fn decode${pascal}With(${decodeParams()}) ${ERR}!${valueType} {`);
  const decBody = emitDecodeValue(inlineField, emit, "result", "result", "    ");
  lines.push(...discardsFor(decBody, [[ALLOC, ALLOC], [DEC, DEC], [ROOT, ROOT]], "    "));
  lines.push(`    var result: ${valueType} = undefined;`);
  lines.push(...decBody);
  lines.push(`    return result;`);
  lines.push(`}`);

  return lines;
}

// Re-export for callers that import from the package barrel.
export { ZigNotImplemented };
export const _threadingProof = { encodeArgs, decodeArgs };
