import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";

import { copyRuntimeFile, vendoredRuntimeBanner } from "../../cli/vendored-runtime.js";

interface TestCheck {
  description: string;
  passed: boolean;
  message?: string;
}

function assert(condition: boolean, message: string): void {
  if (!condition) {
    throw new Error(message);
  }
}

/**
 * The runtime files the CLI copies into a consumer's tree are indistinguishable
 * from hand-written source once they land, which is how a downstream lint fix
 * came to be applied to a vendored copy and then silently reverted by the next
 * regeneration. The banner is the only thing standing between a reader and
 * repeating that. These checks pin the parts of it that carry the meaning.
 */
export function runVendoredRuntimeBannerTests(): {
  passed: number;
  failed: number;
  checks: TestCheck[];
} {
  const checks: TestCheck[] = [];

  // It must say, in the file, that the file is generated and must not be
  // hand-edited — and it must name where to go instead. A banner that only
  // says "generated" leaves the reader with nowhere to take the fix.
  const rust = vendoredRuntimeBanner("rust/src/");
  assert(rust.includes("DO NOT EDIT"), "banner must carry a DO NOT EDIT marker");
  assert(rust.includes("rust/src/"), "banner must name the upstream directory");
  assert(
    rust.includes("silently reverted"),
    "banner must say what happens to an edit, not just forbid it",
  );

  // Every line is a comment in the target language, or the file stops
  // compiling the moment the banner is added.
  const bannerLines = (banner: string) => banner.split("\n").filter((l) => l.length > 0);
  assert(
    bannerLines(rust).every((l) => l.startsWith("//")),
    "every non-empty banner line must be a // comment by default",
  );
  const python = vendoredRuntimeBanner("python/runtime/", "#");
  assert(
    bannerLines(python).every((l) => l.startsWith("#")),
    "every non-empty banner line must use the requested comment prefix",
  );
  assert(!python.includes("//"), "python banner must not leak // comments");

  // The trailing blank line is not cosmetic. Go binds a comment sitting
  // directly above `package x` as the package doc; Zig and Rust do the same
  // for the first declaration. Without the separator the banner would
  // silently replace the runtime file's own documentation.
  assert(rust.endsWith("\n\n"), "banner must end with a blank line separating it from the content");

  // Round-trip through an actual copy: content preserved byte-for-byte after
  // the banner, nothing dropped or reordered.
  const dir = mkdtempSync(join(tmpdir(), "binschema-banner-"));
  try {
    const src = join(dir, "src.go");
    const dest = join(dir, "dest.go");
    const body = "// ABOUTME: thing\n\npackage runtime\n\nfunc F() {}\n";
    writeFileSync(src, body, "utf-8");
    copyRuntimeFile(src, dest, "go/runtime/");

    const out = readFileSync(dest, "utf-8");
    assert(out.startsWith("// @generated by binschema"), "copied file must start with the banner");
    assert(out.endsWith(body), "copied file must preserve the source content verbatim");
    assert(
      out === vendoredRuntimeBanner("go/runtime/") + body,
      "copied file must be exactly banner + content",
    );
    assert(
      out.includes("\n\n// ABOUTME: thing"),
      "a blank line must separate the banner from the original first comment",
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }

  checks.push({ description: "vendored runtime banner assertions", passed: true });

  return { passed: 1, failed: 0, checks };
}
